import type { Metadata } from 'next';
import Provider from '../../providers/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <Provider>
          <div>{children}</div>
        </Provider>
      </body>
    </html>
  );
}
